name: mgeo
channels:
    - conda-forge
dependencies:
    - python>=3.7
    - numpy>=1.7
    - scipy>=1.0.0
    - scikit-learn>=0.22
    - pymatsolver>=0.1.1
    - matplotlib
    - properties>=0.5.2
    - vectormath>=0.2.0
    - discretize>=0.7.0
    - geoana>=0.0.4
    - empymod
    - pandas
    - mkl
    - pyvista
    - spyder
    - jupyter